markdown: rdiscount
pygments: true

author: Riot M
email: minimalisticriot@yahoo.com
title: Riot M
url: http://minimalisticriot.github.com
images: http://minimalisticriot.github.com/images
tabs: [about, archive, projects]
